"""
PyMOL export functionality for HBAT interactions.

Generates PyMOL scripts to visualize hydrogen bonds, halogen bonds, π-interactions,
and other molecular interactions detected by HBAT.

Exports both the PDB structure file and PyMOL visualization script for easy loading
and visualization in PyMOL.
"""

import os
from typing import List, Optional, Set, Tuple
from ..core.interactions import (
    HydrogenBond,
    HalogenBond,
    PiInteraction,
    PiPiInteraction,
    CarbonylInteraction,
    NPiInteraction,
    WaterBridge,
)
from .minimal_pdb_extractor import format_structure_as_pdb


class PyMOLExporter:
    """Export HBAT interactions as PyMOL visualization scripts and PDB files."""

    def __init__(self, pdb_file_path: str, parser=None):
        """Initialize PyMOL exporter.

        :param pdb_file_path: Full path or filename for the PDB file
        :type pdb_file_path: str
        :param parser: PDBParser instance with loaded structure (optional)
        :type parser: Optional[PDBParser]
        """
        # Extract just the filename from the path for the script
        self.pdb_file_path = pdb_file_path
        self.pdb_filename = os.path.basename(pdb_file_path)
        self.parser = parser
        self.script_lines: List[str] = []
        # Track residues for visualization
        self.residues_for_sticks: Set[Tuple[str, int]] = set()  # (chain, resi) tuples for show sticks
        self.residues_for_spheres: Set[Tuple[str, int]] = set()  # (chain, resi) tuples for show spheres

    def add_header(self, title: str = "HBAT Interaction Analysis") -> None:
        """Add PyMOL script header.

        :param title: Title for the visualization
        :type title: str
        """
        self.script_lines.append("#!/usr/bin/env pymol")
        self.script_lines.append("# HBAT Interaction Analysis for PyMOL")
        self.script_lines.append("# Generated by HBAT (Hydrogen Bond Analysis Tool)")
        self.script_lines.append("")
        self.script_lines.append(f"load {self.pdb_filename}")
        self.script_lines.append("bg_color white")
        self.script_lines.append("set sphere_scale, 0.5")
        self.script_lines.append("")

    def add_hydrogen_bonds(self, h_bonds: List[HydrogenBond]) -> None:
        """Add hydrogen bond visualization.

        :param h_bonds: List of HydrogenBond objects
        :type h_bonds: List[HydrogenBond]
        """
        if not h_bonds:
            return

        self.script_lines.append("# Hydrogen Bonds")
        self.script_lines.append("set_color hb_color, [0.2, 0.5, 1.0]")

        for i, hb in enumerate(h_bonds):
            donor = hb.get_donor()
            acceptor = hb.get_acceptor()

            if not (hasattr(donor, 'res_seq') and hasattr(acceptor, 'res_seq')):
                continue

            # Track residues for visualization
            self.residues_for_sticks.add((donor.chain_id, donor.res_seq))
            self.residues_for_sticks.add((acceptor.chain_id, acceptor.res_seq))

            # Create selection names
            donor_sel = f"hb_donor_{i}"
            acceptor_sel = f"hb_acceptor_{i}"
            hb_dist_sel = f"hb_dist_{i}"

            # Create selections for distance objects
            self.script_lines.append(
                f"select {donor_sel}, chain {donor.chain_id} and resi {donor.res_seq} and name {donor.name}"
            )
            self.script_lines.append(
                f"select {acceptor_sel}, chain {acceptor.chain_id} and resi {acceptor.res_seq} and name {acceptor.name}"
            )

            # Draw distance
            self.script_lines.append(
                f"distance {hb_dist_sel}, {donor_sel}, {acceptor_sel}"
            )
            self.script_lines.append(f"hide labels, {hb_dist_sel}")
            self.script_lines.append(f"color hb_color, {hb_dist_sel}")
            self.script_lines.append("")

    def add_halogen_bonds(self, xb_bonds: List[HalogenBond]) -> None:
        """Add halogen bond visualization.

        :param xb_bonds: List of HalogenBond objects
        :type xb_bonds: List[HalogenBond]
        """
        if not xb_bonds:
            return

        self.script_lines.append("# Halogen Bonds")
        self.script_lines.append("set_color xb_color, [1.0, 0.5, 0.0]")

        for i, xb in enumerate(xb_bonds):
            donor = xb.get_donor()
            acceptor = xb.get_acceptor()

            if not (hasattr(donor, 'res_seq') and hasattr(acceptor, 'res_seq')):
                continue

            # Track residues for visualization
            self.residues_for_sticks.add((donor.chain_id, donor.res_seq))
            self.residues_for_sticks.add((acceptor.chain_id, acceptor.res_seq))

            donor_sel = f"xb_donor_{i}"
            acceptor_sel = f"xb_acceptor_{i}"
            xb_dist_sel = f"xb_dist_{i}"

            self.script_lines.append(
                f"select {donor_sel}, chain {donor.chain_id} and resi {donor.res_seq} and name {donor.name}"
            )
            self.script_lines.append(
                f"select {acceptor_sel}, chain {acceptor.chain_id} and resi {acceptor.res_seq} and name {acceptor.name}"
            )

            self.script_lines.append(f"distance {xb_dist_sel}, {donor_sel}, {acceptor_sel}")
            self.script_lines.append(f"hide labels, {xb_dist_sel}")
            self.script_lines.append(f"color xb_color, {xb_dist_sel}")
            self.script_lines.append("")
            self.script_lines.append("")

    def add_pi_interactions(self, pi_interactions: List[PiInteraction]) -> None:
        """Add π-interaction visualization.

        :param pi_interactions: List of PiInteraction objects
        :type pi_interactions: List[PiInteraction]
        """
        if not pi_interactions:
            return

        self.script_lines.append("# Pi-Interactions")
        self.script_lines.append("set_color pi_color, [1.0, 0.2, 0.8]  # Magenta")

        for i, pi in enumerate(pi_interactions):
            donor = pi.get_donor()

            if not hasattr(donor, 'res_seq'):
                continue

            # Track residues for visualization
            self.residues_for_sticks.add((donor.chain_id, donor.res_seq))

            # Track pi system residue
            if pi.pi_atoms:
                pi_atom = pi.pi_atoms[0]
                self.residues_for_sticks.add((pi_atom.chain_id, pi_atom.res_seq))

            donor_sel = f"pi_donor_{i}"
            pi_center_pseudo = f"pi_center_{i}"
            pi_dist_sel = f"pi_dist_{i}"

            self.script_lines.append(
                f"select {donor_sel}, chain {donor.chain_id} and resi {donor.res_seq} and name {donor.name}"
            )

            self.script_lines.append(f"color pi_color, {donor_sel}")

            # Create pseudoatom at pi center for distance visualization
            self.script_lines.append(
                f"pseudoatom {pi_center_pseudo}, pos=[{pi.pi_center.x}, {pi.pi_center.y}, {pi.pi_center.z}]"
            )

            # Draw distance line from donor to pi center
            self.script_lines.append(
                f"distance {pi_dist_sel}, {donor_sel}, {pi_center_pseudo}"
            )
            self.script_lines.append(f"hide labels, {pi_dist_sel}")
            self.script_lines.append(f"color pi_color, {pi_dist_sel}")
            self.script_lines.append("")

    def add_pi_pi_stacking(self, stacking: List[PiPiInteraction]) -> None:
        """Add π-π stacking visualization.

        :param stacking: List of PiPiInteraction objects
        :type stacking: List[PiPiInteraction]
        """
        if not stacking:
            return

        self.script_lines.append("# Pi-Pi Stacking")
        self.script_lines.append("set_color ring1_color, [0.0, 1.0, 1.0]  # Cyan")
        self.script_lines.append("set_color ring2_color, [1.0, 0.0, 1.0]  # Magenta")
        self.script_lines.append("set_color pipi_dist_color, [1.0, 0.5, 0.0]  # Orange")

        for i, stack in enumerate(stacking):
            ring1 = stack.get_ring1()
            ring2 = stack.get_ring2()

            if not (hasattr(ring1, 'res_seq') and hasattr(ring2, 'res_seq')):
                continue

            # Track residues for visualization
            self.residues_for_sticks.add((ring1.chain_id, ring1.res_seq))
            self.residues_for_sticks.add((ring2.chain_id, ring2.res_seq))

            ring1_sel = f"pipi_ring1_{i}"
            ring2_sel = f"pipi_ring2_{i}"
            ring1_center_pseudo = f"pipi_ring1_center_{i}"
            ring2_center_pseudo = f"pipi_ring2_center_{i}"
            pipi_dist_sel = f"pipi_dist_{i}"

            self.script_lines.append(
                f"select {ring1_sel}, chain {ring1.chain_id} and resi {ring1.res_seq}"
            )
            self.script_lines.append(
                f"select {ring2_sel}, chain {ring2.chain_id} and resi {ring2.res_seq}"
            )
            self.script_lines.append(f"color ring1_color, {ring1_sel}")
            self.script_lines.append(f"color ring2_color, {ring2_sel}")

            # Create pseudoatoms at ring centers for distance visualization
            self.script_lines.append(
                f"pseudoatom {ring1_center_pseudo}, pos=[{stack.ring1_center.x}, {stack.ring1_center.y}, {stack.ring1_center.z}]"
            )
            self.script_lines.append(
                f"pseudoatom {ring2_center_pseudo}, pos=[{stack.ring2_center.x}, {stack.ring2_center.y}, {stack.ring2_center.z}]"
            )

            # Draw distance line from ring center to ring center
            self.script_lines.append(
                f"distance {pipi_dist_sel}, {ring1_center_pseudo}, {ring2_center_pseudo}"
            )
            self.script_lines.append(f"hide labels, {pipi_dist_sel}")
            self.script_lines.append(f"color pipi_dist_color, {pipi_dist_sel}")
            self.script_lines.append("")

    def add_water_bridges(self, bridges: List[WaterBridge]) -> None:
        """Add water bridge visualization.

        :param bridges: List of WaterBridge objects
        :type bridges: List[WaterBridge]
        """
        if not bridges:
            return

        self.script_lines.append("# Water Bridges")
        self.script_lines.append("set_color wbridge_color, [0.2, 0.6, 1.0]")

        for i, bridge in enumerate(bridges):
            donor_atom = bridge.get_donor()
            acceptor_atom = bridge.get_acceptor()

            donor_parts = bridge.get_donor_residue().split(":")
            acceptor_parts = bridge.get_acceptor_residue().split(":")

            donor_chain = donor_parts[0]
            donor_resi = int(donor_parts[2])
            acceptor_chain = acceptor_parts[0]
            acceptor_resi = int(acceptor_parts[2])

            # Track protein residues
            self.residues_for_sticks.add((donor_chain, donor_resi))
            self.residues_for_sticks.add((acceptor_chain, acceptor_resi))

            # Get atom names if available
            donor_atom_name = donor_atom.name if hasattr(donor_atom, 'name') else "*"
            acceptor_atom_name = acceptor_atom.name if hasattr(acceptor_atom, 'name') else "*"

            donor_sel = f"wbridge_donor_{i}"
            acceptor_sel = f"wbridge_acceptor_{i}"

            self.script_lines.append(
                f"select {donor_sel}, chain {donor_chain} and resi {donor_resi} and name {donor_atom_name}"
            )
            self.script_lines.append(
                f"select {acceptor_sel}, chain {acceptor_chain} and resi {acceptor_resi} and name {acceptor_atom_name}"
            )
            self.script_lines.append(f"color wbridge_color, {donor_sel}")
            self.script_lines.append(f"color wbridge_color, {acceptor_sel}")

            # Track and show water molecules
            for water_idx, water_res in enumerate(bridge.water_residues):
                water_parts = water_res.split(":")
                water_chain = water_parts[0]
                water_resi = int(water_parts[2])
                self.residues_for_spheres.add((water_chain, water_resi))

                water_sel_unique = f"wbridge_water_{i}_{water_idx}"
                self.script_lines.append(
                    f"select {water_sel_unique}, chain {water_chain} and resi {water_resi}"
                )
                self.script_lines.append(f"set sphere_scale, 0.4, {water_sel_unique}")

            # Draw explicit distance lines for each hydrogen bond in the bridge path
            for hbond_idx, hbond in enumerate(bridge.bridge_path):
                donor = hbond.get_donor()
                acceptor = hbond.get_acceptor()

                if not (
                    hasattr(donor, "chain_id")
                    and hasattr(donor, "res_seq")
                    and hasattr(acceptor, "chain_id")
                    and hasattr(acceptor, "res_seq")
                ):
                    continue

                # Create selection names
                donor_hbond_sel = f"wbridge_hbond_donor_{i}_{hbond_idx}"
                acceptor_hbond_sel = f"wbridge_hbond_acceptor_{i}_{hbond_idx}"
                hbond_dist_sel = f"wbridge_hbond_dist_{i}_{hbond_idx}"

                # Get atom names if available
                donor_atom_name = donor.name if hasattr(donor, 'name') else "*"
                acceptor_atom_name = acceptor.name if hasattr(acceptor, 'name') else "*"

                self.script_lines.append(
                    f"select {donor_hbond_sel}, chain {donor.chain_id} and resi {donor.res_seq} and name {donor_atom_name}"
                )
                self.script_lines.append(
                    f"select {acceptor_hbond_sel}, chain {acceptor.chain_id} and resi {acceptor.res_seq} and name {acceptor_atom_name}"
                )

                # Draw distance line between donor and acceptor
                self.script_lines.append(
                    f"distance {hbond_dist_sel}, {donor_hbond_sel}, {acceptor_hbond_sel}"
                )
                self.script_lines.append(f"hide labels, {hbond_dist_sel}")
                self.script_lines.append(f"color yellow, {hbond_dist_sel}")

            # Create a selection for all water bridge residues (for centering/zooming)
            all_bridge_resis = [f"resi {donor_resi}"]
            for water_res in bridge.water_residues:
                water_parts = water_res.split(":")
                water_resi = int(water_parts[2])
                all_bridge_resis.append(f"resi {water_resi}")
            all_bridge_resis.append(f"resi {acceptor_resi}")

            bridge_all_sel = f"wbridge_all_{i}"
            resi_str = " or ".join(all_bridge_resis)
            self.script_lines.append(f"select {bridge_all_sel}, ({resi_str})")

            # Center and zoom on water bridge
            self.script_lines.append(f"center {bridge_all_sel}")
            self.script_lines.append(f"zoom {bridge_all_sel}, 2")
            self.script_lines.append("")

    def add_carbonyl_interactions(self, carbonyl_interactions: List[CarbonylInteraction]) -> None:
        """Add carbonyl interaction visualization.

        :param carbonyl_interactions: List of CarbonylInteraction objects
        :type carbonyl_interactions: List[CarbonylInteraction]
        """
        if not carbonyl_interactions:
            return

        self.script_lines.append("# Carbonyl Interactions")
        self.script_lines.append("set_color carbonyl_color, [1.0, 0.6, 0.0]")

        for i, carbonyl in enumerate(carbonyl_interactions):
            donor = carbonyl.get_donor()
            acceptor = carbonyl.get_acceptor()

            if not (hasattr(donor, 'res_seq') and hasattr(acceptor, 'res_seq')):
                continue

            # Track residues for visualization
            self.residues_for_sticks.add((donor.chain_id, donor.res_seq))
            self.residues_for_sticks.add((acceptor.chain_id, acceptor.res_seq))

            donor_sel = f"carbonyl_donor_{i}"
            acceptor_sel = f"carbonyl_acceptor_{i}"
            carbonyl_dist_sel = f"carbonyl_dist_{i}"

            self.script_lines.append(
                f"select {donor_sel}, chain {donor.chain_id} and resi {donor.res_seq} and name {donor.name}"
            )
            self.script_lines.append(
                f"select {acceptor_sel}, chain {acceptor.chain_id} and resi {acceptor.res_seq} and name {acceptor.name}"
            )

            # Draw distance line
            self.script_lines.append(
                f"distance {carbonyl_dist_sel}, {donor_sel}, {acceptor_sel}"
            )
            self.script_lines.append(f"hide labels, {carbonyl_dist_sel}")
            self.script_lines.append(f"color carbonyl_color, {carbonyl_dist_sel}")
            self.script_lines.append("")

    def add_n_pi_interactions(self, n_pi_interactions: List[NPiInteraction]) -> None:
        """Add N-π interaction visualization.

        :param n_pi_interactions: List of NPiInteraction objects
        :type n_pi_interactions: List[NPiInteraction]
        """
        if not n_pi_interactions:
            return

        self.script_lines.append("# N-Pi Interactions")
        self.script_lines.append("set_color npi_color, [0.2, 1.0, 0.8]")

        for i, npi in enumerate(n_pi_interactions):
            donor = npi.get_donor()

            if not hasattr(donor, 'res_seq'):
                continue

            # Track residues for visualization
            self.residues_for_sticks.add((donor.chain_id, donor.res_seq))

            # Track pi system residue
            if npi.pi_atoms:
                pi_atom = npi.pi_atoms[0]
                self.residues_for_sticks.add((pi_atom.chain_id, pi_atom.res_seq))

            donor_sel = f"npi_donor_{i}"
            pi_center_pseudo = f"npi_center_{i}"
            npi_dist_sel = f"npi_dist_{i}"

            self.script_lines.append(
                f"select {donor_sel}, chain {donor.chain_id} and resi {donor.res_seq} and name {donor.name}"
            )

            self.script_lines.append(f"color npi_color, {donor_sel}")

            # Create pseudoatom at pi center for distance visualization
            self.script_lines.append(
                f"pseudoatom {pi_center_pseudo}, pos=[{npi.pi_center.x}, {npi.pi_center.y}, {npi.pi_center.z}]"
            )

            # Draw distance line from donor to pi center
            self.script_lines.append(
                f"distance {npi_dist_sel}, {donor_sel}, {pi_center_pseudo}"
            )
            self.script_lines.append(f"hide labels, {npi_dist_sel}")
            self.script_lines.append(f"color npi_color, {npi_dist_sel}")
            self.script_lines.append("")

    def add_footer(self) -> None:
        """Add PyMOL script footer with visualization settings."""
        self.script_lines.append("")
        self.script_lines.append("# Final visualization")
        self.script_lines.append("hide all")

        # Build explicit show sticks command with all tracked residues
        if self.residues_for_sticks:
            sticks_list = sorted(self.residues_for_sticks)
            sticks_sel = " or ".join(f"(chain {chain} and resi {resi})" for chain, resi in sticks_list)
            self.script_lines.append(f"show sticks, {sticks_sel}")

        # Build explicit show spheres command for water/ligands
        if self.residues_for_spheres:
            spheres_list = sorted(self.residues_for_spheres)
            spheres_sel = " or ".join(f"(chain {chain} and resi {resi})" for chain, resi in spheres_list)
            self.script_lines.append(f"show spheres, {spheres_sel}")

        # Show all distance objects (dashes)
        self.script_lines.append("show dashes")

        # Set visualization parameters
        self.script_lines.append("set stick_radius, 0.2")
        self.script_lines.append("set dash_width, 1.0")
        self.script_lines.append("set dash_gap, 0.1")
        self.script_lines.append("set dash_length, 0.3")
        self.script_lines.append("bg_color white")
        self.script_lines.append("set antialias, 2")
        self.script_lines.append("")
        self.script_lines.append("zoom visible")
        self.script_lines.append("# End of HBAT PyMOL script")

    def get_script(self) -> str:
        """Get the complete PyMOL script.

        :returns: PyMOL script as string
        :rtype: str
        """
        return "\n".join(self.script_lines)

    def save_script(self, output_file: str) -> bool:
        """Save PyMOL script to file.

        :param output_file: Path to output PyMOL script file
        :type output_file: str
        :returns: True if saved successfully, False otherwise
        :rtype: bool
        """
        try:
            with open(output_file, "w") as f:
                f.write(self.get_script())
            print(f"PyMOL script saved: {output_file}")
            return True
        except Exception as e:
            print(f"Error saving PyMOL script: {e}")
            return False

    def save_pdb(self, output_file: str) -> bool:
        """Save PDB structure file.

        :param output_file: Path to output PDB file
        :type output_file: str
        :returns: True if saved successfully, False otherwise
        :rtype: bool
        """
        if not self.parser:
            print("Error: No parser provided. Cannot save PDB file.")
            return False

        try:
            pdb_content = format_structure_as_pdb(self.parser)
            with open(output_file, "w") as f:
                f.write(pdb_content)
            print(f"PDB file saved: {output_file}")
            return True
        except Exception as e:
            print(f"Error saving PDB file: {e}")
            return False

    def save(self, output_file: str) -> bool:
        """Save PyMOL script to file (deprecated, use save_script instead).

        :param output_file: Path to output PyMOL script file
        :type output_file: str
        :returns: True if saved successfully, False otherwise
        :rtype: bool
        """
        return self.save_script(output_file)

    def export_package(self, output_dir: str, basename: str = "hbat_pymol") -> bool:
        """Export complete PyMOL visualization package with PDB and script.

        Creates a directory with both the PDB structure file and PyMOL visualization
        script. Both files use the same basename for easy reference.

        :param output_dir: Directory to save the package
        :type output_dir: str
        :param basename: Base name for files (without extension)
        :type basename: str
        :returns: True if export successful, False otherwise
        :rtype: bool

        **Example:**

        .. code-block:: python

            exporter.export_package("./pymol_visualizations", "protein_analysis")

            # Creates:
            # - pymol_visualizations/protein_analysis.pdb
            # - pymol_visualizations/protein_analysis.pml
        """
        try:
            # Create output directory if it doesn't exist
            os.makedirs(output_dir, exist_ok=True)

            pdb_file = os.path.join(output_dir, f"{basename}.pdb")
            script_file = os.path.join(output_dir, f"{basename}.pml")

            # Save PDB file
            if not self.save_pdb(pdb_file):
                return False

            # Save PyMOL script
            if not self.save_script(script_file):
                return False

            # Create a README file
            readme_file = os.path.join(output_dir, "README.txt")
            readme_content = f"""HBAT PyMOL Visualization Package
================================

Files:
- {basename}.pdb : Structure with all atoms and bonds
- {basename}.pml : PyMOL visualization script

How to use in PyMOL:
1. Open PyMOL
2. Load the structure: File -> Open -> {basename}.pdb
3. Run the script: File -> Run Script -> {basename}.pml

Or from command line:
    pymol {basename}.pdb {basename}.pml

The script will automatically:
- Load the structure
- Display all detected interactions with colors:
  * Blue: Hydrogen bonds
  * Orange: Halogen bonds
  * Magenta: Pi-interactions
  * Cyan: Pi-pi stacking
  * Light Blue: Water bridges
- Set up appropriate visualization styles
- Zoom to show all interactions

For more information, visit:
https://github.com/abhishektiwari/hbat
"""
            with open(readme_file, "w") as f:
                f.write(readme_content)

            print(f"PyMOL visualization package exported to: {output_dir}")
            print(f"  - {pdb_file}")
            print(f"  - {script_file}")
            print(f"  - {readme_file}")
            return True

        except Exception as e:
            print(f"Error exporting PyMOL package: {e}")
            return False


def export_interactions_to_pymol(
    pdb_file_path: str,
    hydrogen_bonds: Optional[List[HydrogenBond]] = None,
    halogen_bonds: Optional[List[HalogenBond]] = None,
    pi_interactions: Optional[List[PiInteraction]] = None,
    pi_pi_stacking: Optional[List[PiPiInteraction]] = None,
    carbonyl_interactions: Optional[List[CarbonylInteraction]] = None,
    n_pi_interactions: Optional[List[NPiInteraction]] = None,
    water_bridges: Optional[List[WaterBridge]] = None,
    output_file: str = "hbat_interactions.pml",
    parser=None,
    output_dir: Optional[str] = None,
) -> bool:
    """Export HBAT interactions as PyMOL visualization package.

    Generates a complete PyMOL visualization package with PDB structure file
    and PyMOL script. Both files are ready to use in PyMOL.

    **Example:**

    .. code-block:: python

        from hbat.visualization import export_interactions_to_pymol
        from hbat import NPMolecularInteractionAnalyzer

        analyzer = NPMolecularInteractionAnalyzer()
        analyzer.analyze_file("protein.pdb")

        # Determine which PDB file to use
        pdb_file = analyzer._pdb_fixing_info.get("fixed_file_path")
        if not pdb_file or not os.path.exists(pdb_file):
            pdb_file = analyzer._pdb_fixing_info.get("input_file_path")

        # Export with full PDB and script
        export_interactions_to_pymol(
            pdb_file_path=pdb_file,
            parser=analyzer.parser,
            hydrogen_bonds=analyzer.hydrogen_bonds,
            halogen_bonds=analyzer.halogen_bonds,
            water_bridges=analyzer.water_bridges,
            output_dir="./pymol_analysis"
        )

        # Then in PyMOL:
        # pymol pymol_analysis/<basename>.pdb pymol_analysis/<basename>.pml

    :param pdb_file_path: Full path to the PDB file to visualize
    :type pdb_file_path: str
    :param hydrogen_bonds: List of HydrogenBond objects (optional)
    :type hydrogen_bonds: Optional[List[HydrogenBond]]
    :param halogen_bonds: List of HalogenBond objects (optional)
    :type halogen_bonds: Optional[List[HalogenBond]]
    :param pi_interactions: List of PiInteraction objects (optional)
    :type pi_interactions: Optional[List[PiInteraction]]
    :param pi_pi_stacking: List of PiPiInteraction objects (optional)
    :type pi_pi_stacking: Optional[List[PiPiInteraction]]
    :param carbonyl_interactions: List of CarbonylInteraction objects (optional)
    :type carbonyl_interactions: Optional[List[CarbonylInteraction]]
    :param n_pi_interactions: List of NPiInteraction objects (optional)
    :type n_pi_interactions: Optional[List[NPiInteraction]]
    :param water_bridges: List of WaterBridge objects (optional)
    :type water_bridges: Optional[List[WaterBridge]]
    :param output_file: Output PyMOL script filename (deprecated, use output_dir)
    :type output_file: str
    :param parser: PDBParser instance with structure (optional, needed for PDB export)
    :type parser: Optional[PDBParser]
    :param output_dir: Output directory for complete package (optional)
    :type output_dir: Optional[str]
    :returns: True if export successful, False otherwise
    :rtype: bool
    """
    exporter = PyMOLExporter(pdb_file_path, parser=parser)

    exporter.add_header("HBAT Interaction Analysis for PyMOL")

    if hydrogen_bonds:
        exporter.add_hydrogen_bonds(hydrogen_bonds)

    if halogen_bonds:
        exporter.add_halogen_bonds(halogen_bonds)

    if pi_interactions:
        exporter.add_pi_interactions(pi_interactions)

    if pi_pi_stacking:
        exporter.add_pi_pi_stacking(pi_pi_stacking)

    if carbonyl_interactions:
        exporter.add_carbonyl_interactions(carbonyl_interactions)

    if n_pi_interactions:
        exporter.add_n_pi_interactions(n_pi_interactions)

    if water_bridges:
        exporter.add_water_bridges(water_bridges)

    exporter.add_footer()

    # If output_dir is provided, export complete package with PDB and script
    if output_dir:
        basename = os.path.splitext(os.path.basename(pdb_file_path))[0]
        return exporter.export_package(output_dir, basename)
    else:
        # Otherwise, just save the script file
        return exporter.save_script(output_file)
